feat: Add Python analogues of Java templates
flawgarden/templates-db pull request #17
Opened 2024-08-20 13:59 UTC by ch3zych3z

2024-08-22 13:11 UTC, DaniilStepanov requested changes
Globally do not use ~[BODY]~ in python templates
And add empty_line to each file if not added

2024-08-25 15:15 UTC, ch3zych3z commented on languages/python/sensitivity/lambdas/helpers/UnaryOpMutationInterface.tmt
> +~class UnaryOpMutationInterface start~
Why `fun` is assigned to `self._mutate_func`? With given realization of `mutate` `fun` won't be called

2024-08-25 15:21 UTC, ch3zych3z commented on languages/python/sensitivity/virtuality/helpers/DerivedBinaryOpClass.tmt
> +~class DerivedBinaryOpClass1 start~
What are the rules of injected classes import? It was discussed at the meetings that there's no knowledge of locations where injected classes will be placed

2024-08-25 15:22 UTC, ch3zych3z commented on languages/python/sensitivity/virtuality/helpers/ImplBinaryOpInterfaceClass.tmt
> +~class ImplBinaryOpInterfaceClass1 start~
Same question as at `DerivedBinaryOpClass1.tmt`

2024-08-25 15:30 UTC, ch3zych3z commented
> Globally do not use ~[BODY]~ in python templates And add empty_line to each file if not added

What does it mean? Should templates with \~[BODY]\~ be removed?

Also replied in review discussion. Unreplied ones are fixed

2024-08-27 07:51 UTC, DaniilStepanov commented on languages/python/sensitivity/lambdas/helpers/UnaryOpMutationInterface.tmt
> +~class UnaryOpMutationInterface start~
ok. no fix needed

2024-08-27 07:53 UTC, DaniilStepanov commented on languages/python/sensitivity/virtuality/helpers/DerivedBinaryOpClass.tmt
> +~class DerivedBinaryOpClass1 start~
They will be located in the same directory with chosen file for mutation

2024-08-27 07:53 UTC, DaniilStepanov commented on languages/python/sensitivity/virtuality/helpers/ImplBinaryOpInterfaceClass.tmt
> +~class ImplBinaryOpInterfaceClass1 start~
Same answer

2024-08-27 07:55 UTC, DaniilStepanov commented
> > Globally do not use ~[BODY]~ in python templates And add empty_line to each file if not added
> 
> What does it mean? Should templates with ~[BODY]~ be removed? Are imports from `typing` are needed? Why not just `from typing import *` for almost every injected file?
> 
> Also replied in review discussions. Unreplied ones are fixed

1. No, just delete ~[BODY]~ constructions
2. Imports from typing are needed, because we are not modifying helper classes

2024-09-20 11:18 UTC, DaniilStepanov approved these changes

2024-09-20 11:19 UTC, merged